version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    restart: unless-stopped
    command: 
      --default-authentication-plugin=mysql_native_password
      --sql_mode=NO_ENGINE_SUBSTITUTION
    ports:
      - '${MYSQL_MASTER_PORT}:3306'
    volumes:
      - '.build/dev/mysql/master/db:/var/lib/mysql'
      - '.build/dev/mysql/master/my.cnf:/etc/mysql/conf.d/custom.cnf'
      - '.build/dev/mysql/up.sql:/docker-entrypoint-initdb.d/01-up.sql'
    environment:
      - 'TZ:${TZ}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    networks:
      - local

  mysql-slave:
    image: mysql:8.0
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode=NO_ENGINE_SUBSTITUTION
      --log-bin=mysql-bin
      --server-id=2
    restart: unless-stopped
    depends_on:
      - mysql-master
    ports:
      - '${MYSQL_SLAVE_PORT}:3306'
    volumes:
      - '.build/dev/mysql/slave/db:/var/lib/mysql'
      - '.build/dev/mysql/slave/my.cnf:/etc/mysql/conf.d/custom.cnf'
      - '.build/dev/mysql/up.sql:/docker-entrypoint-initdb.d/01-up.sql'
    environment:
      - 'TZ:${TZ}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    networks:
      - local

networks:
  local:
